language: node_js
sudo: required
node_js:
  - '6'

dist: xenial

env:
  - browser=chrome

addons:
  chrome: stable

before_script:
  - |
    case $browser in
      chrome)
        sudo apt-get update -qq && sudo apt-get install -y chromium-chromedriver
        export PATH=$PATH:/usr/lib/chromium-browser/
        chromedriver -v
        ;;
    esac

services:
  - xvfb

script:
  - ./scripts/travis/build.sh

branches:
  only:
    - master