name: Run Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Checkout
      uses: actions/checkout@v1

    - name: Install and Test
      run: |
        npm ci
        grunt test
      env:
        CI: true
