name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install and Test
        run: |
          rm .npmrc
          npm install
          xvfb-run --auto-servernum grunt test
        env:
          CI: true
